### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [ekzhu/lshensemble#2]
I am rather puzzled as this tool used to have a license and you removed it with https://github.com/ekzhu/lshensemble/commit/95a999a6652e9ab1805380db7ddf823394895c22 .... what is the license then after this commit? Without a license, none can uses this.

**Comment by ekzhu** [comment]
Late to this... Just added a license. Thanks.

**Comment by pombredanne** [comment]
@ekzhu Thanks!
